version: '3.8'

services:
  app:
    build: .
    env_file:
      - config.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./data:/app/data
  db:
    image: postgres:13
    env_file:
      - config.env
    ports:
      - "5432:5432"